### PR TITLE
Add Essence to glossary, etc.

### PR DESCRIPTION
**Pull request by garethsb**
Resolving outstanding work from #62.

What about "signal" and "stream". Could we just use these words in the definition of Source and Sender/Receiver respectively?

### CODE REVIEW

**Comment by garethsb** [comment]
Something like:

For example, a Sender could transmit an RTP stream according to a payload mapping for a specific video format, or a sequence of data Grains via the MQTT or WebSocket protocols.

For example, a Source could generate Essence based on its Device's input signals. (Should we be more explicit, e.g. "camera image sensor", "HDMI input signal", "received RTP streams", "test pattern", "file", etc.?)

**Comment by pedro-alves-ferreira** [comment]
LGTM. I think examples always help.

For example, a Source could generate Essence based on its Device's input signals, such as camera image sensor, HDMI input signal, received RTP streams, internally generated test pattern, file, etc.

**Comment by garethsb** [comment]
Add examples, thanks, @pedro-alves-ferreira.

**Comment by cristian-recoseanu** [comment]
These changes look great to me. Much more encompassing than before and I like the examples introducing essence and signal.

**Review by cristian-recoseanu — APPROVED** [review]

**Review by peterbrightwell — APPROVED** [review]

**Pull request merged**
